package ru.practicum.crm.user.domain;

/** Допустимые коды прав, хранящихся в каталоге доступа. */
public enum PermissionCode {
    REQUEST_CREATE,
    REQUEST_READ_OWN,
    REQUEST_READ_ALL,
    REQUEST_CANCEL_OWN,
    REQUEST_STATUS_CHANGE,
    REQUEST_ASSIGN,
    REQUEST_EDIT,
    REQUEST_AUDIT_READ,
    COMMENT_PUBLIC_CREATE_OWN,
    COMMENT_PUBLIC_CREATE,
    COMMENT_INTERNAL_CREATE,
    ATTACHMENT_CREATE_OWN,
    ATTACHMENT_READ_OWN,
    ATTACHMENT_MANAGE,
    PROFILE_READ_OWN,
    PROFILE_EDIT_OWN,
    USER_READ,
    USER_MANAGE,
    ROLE_MANAGE,
    TENANT_SETTINGS_READ,
    TENANT_SETTINGS_MANAGE,
    REQUEST_TYPE_MANAGE,
    SLA_POLICY_MANAGE,
    INTEGRATION_MANAGE,
    ANALYTICS_READ
}
