spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: ${app.database.url}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver

  mail:
    host: ${app.mail.host}
    port: ${app.mail.port}
    username: ${app.mail.username}
    password: ${app.mail.password}
    properties:
      mail:
        smtp:
          auth: ${app.mail.auth}
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      env: prod

app:
  database:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    auth: true
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
